services:
  db:
    image: postgres:16
    container_name: halfyourbook_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: halfyourbook
    ports:
      - "5433:5432"
    volumes:
      - halfyourbook_pg:/var/lib/postgresql/data

volumes:
  halfyourbook_pg:
